kind: Service
apiVersion: v1
metadata:
  labels:
    app: traefik-ingress
  name: traefik-ingress
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: traefik-ingress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: traefik
spec:
 rules:
   - host: traefik.rktnetes
     http:
       paths:
         - path: /
           backend:
             serviceName: traefik-ingress
             servicePort: 8080
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: traefik-ingress
  labels:
    app: traefik-ingress
spec:
  replicas: 1
  selector:
    app: traefik-ingress
  template:
    metadata:
      labels:
        app: traefik-ingress
        name: traefik-ingress
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-ingress
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        - containerPort: 8080
        args:
        - --web
        - --kubernetes
        - --logLevel=DEBUG
